### ISSUE TITLE
Resulting Schema resulted in offline: handler 'handler'  is not a function

### ISSUE THREAD

**Issue by yoshikimiki** [MichalLytek/type-graphql#1256]
**Describe the Bug**
Passing in the resulting schema to apollo-server-lambda results in `offline: handler 'handler'  is not a function`. I'm pretty sure the issue comes from `type-graphql` since the below code snippet works fine with their tutorial.

**To Reproduce**
authorization-resolver is just a simple resolve that returns a dummy value.

graphql.ts
```
import { ApolloServer, gql } from 'apollo-server-lambda';
import { LambdaContextFunctionParams } from "apollo-server-lambda/dist/ApolloServer";
import { ThirdPartyAuthorizationResolver } from "./resolvers/authorization-resolver";
import { buildSchema } from "type-graphql";

const schema = await buildSchema({
    resolvers: [ThirdPartyAuthorizationResolver],
  });

const server = new ApolloServer({
    schema,
    context: (request: LambdaContextFunctionParams) => {
        console.log(request)
    }
});

export const handler = server.createHandler();
```

serverless.yml
```
service: local-serverless-test-use-only-see-cloud-infrastructure-for-actual-setup

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.[t|j]s # Exclude test files


functions:
  graphql:
    handler: src/graphql.handler
    events:
      - http:
          path: /graphql
          method: POST
      - http:
          path: /graphql
          method: GET


plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-prune-plugin
 ```

**Expected Behavior**
The serverless GraphQL should be able to handle the request

**Logs**
```
POST /graphql (λ: graphql)
✖ offline: handler 'handler' in /Users/allen/Projects/Website-APIs/.webpack/service/src/graphql is not a function
✖ Error: offline: handler 'handler' in /Users/allen/Projects/Website-APIs/.webpack/service/src/graphql is not a function
      at InProcessRunner.run (/Users/allen/Projects/Website-APIs/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:160:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async LambdaFunction.runHandler (/Users/allen/Projects/Website-APIs/node_modules/serverless-offline/dist/lambda/LambdaFunction.js:368:20)
      at async hapiHandler (/Users/allen/Projects/Website-APIs/node_modules/serverless-offline/dist/events/http/HttpServer.js:740:18)
      at async exports.Manager.execute (/Users/allen/Projects/Website-APIs/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
      at async Object.internals.handler (/Users/allen/Projects/Website-APIs/node_modules/@hapi/hapi/lib/handler.js:46:20)
      at async exports.execute (/Users/allen/Projects/Website-APIs/node_modules/@hapi/hapi/lib/handler.js:31:20)
      at async Request._lifecycle (/Users/allen/Projects/Website-APIs/node_modules/@hapi/hapi/lib/request.js:371:32)
      at async Request._execute (/Users/allen/Projects/Website-APIs/node_modules/@hapi/hapi/lib/request.js:281:9)
```

**Environment (please complete the following information):**

- OS: Mac
- Node v16.14.0
- Package version: 1.1.1
- TypeScript version 4.6.3
**Additional Context**
I'm pretty sure that the issue comes from here. I've verified that serverless, serverless-offline,  and apollo-server-lambda work fine in isolation.

**Comment by yoshikimiki** [comment]
Playing around with it more, this error seems to occur from
```
const schema = await buildSchema({
    resolvers: [ThirdPartyAuthorizationResolver],
  });

```
It's not clear to me why calling this would cause the handler to not be a function. It might be related to it being awaited...

**Comment by yoshikimiki** [comment]
Resolved via:
1. Upgrading type-graphql to v1.2.0-rc.1
2. Using the synchronous version instead. Example below:
```
const { typeDefs, resolvers } = buildTypeDefsAndResolversSync({
    resolvers: [ThirdPartyAuthorizationResolver],
  });
```
